version: '3'
services:

    web:
        image: nginx:1.17.10
        volumes:
         - ../source/:/usr/share/nginx/website:cached
         - ./docker/website.template:/etc/nginx/conf.d/default.conf
         - ./docker/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - php
            - db
        command: /bin/bash -c "exec nginx -g 'daemon off;'"
        
    php:
        image: php.website
        volumes:
            - ../source/:/usr/share/nginx/website:cached
        depends_on:
            - db    
        build: 
            context: ./docker/php
        working_dir: /usr/share/nginx/website
        
    db:
        image: mysql:5.7
        volumes:
            - ./docker/mysql:/var/lib/mysql
        ports:
            - 3306:3306
        restart: always
        environment:
           - MYSQL_ROOT_PASSWORD=v3ryHrrd33PssW
           - MYSQL_USER=dbuser
           - MYSQL_PASSWORD=v3ryHrrd33PssW

